version: '3.7'
services:
  configserver:
    container_name: configserver
    image: pavanbaloju/spring-config-server:latest
    ports:
      - "8081:8888"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"